//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.example.commomadapter.utils;

import android.content.Context;

public final class PersonAdapter_
    extends PersonAdapter
{

    private Context context_;

    private PersonAdapter_(Context context) {
        context_ = context;
        init_();
    }

    public static PersonAdapter_ getInstance_(Context context) {
        return new PersonAdapter_(context);
    }

    private void init_() {
        context = context_;
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
